### ISSUE TITLE
Weekly Scrum - [March 8 2018]

### ISSUE THREAD

**Issue by lavatahir** [lavatahir/Perkpack#7]
- I have worked on the card entity, the card rest controller, and the display for showing the cards in the system and adding new cards through a form, and a rest controller test
- I will be working on adding more functionality for cards (linking them with perks and their creator (user), and working on the rest/react front end
- Nothing is holding me back (other than learning react)

**Comment by vanjaveselinovic** [comment]
Vanja:
- I set up React and started preliminary frontend work

**Comment by cyruscse** [comment]
Cyrus:
- I created the Perk model, repository, and controllers
- I created a basic page to create and vote on Perks

For the next iteration:
- I want to be able to link Perks to Cards and to the User that created them.
- I want to improve the front end for the Perk view

**Comment by afarah613** [comment]
- I have been working on the user model, the rest api for the user model as well as the tests
- I will be working on logging in and out for a user, adding cards to a user and the ui for the user
- nothing is blocking me
